service: munimap-proxy

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager

custom:
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: proxy.munimap.online
    certificateName: '*.munimap.online'
    basePath: ''
    stage: dev

functions:
  aws:
    handler: server.aws
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
